name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true

    - name: Install compatible RubyGems version
      run: |
        gem install rubygems-update -v 3.3.26  # Install a version compatible with Ruby 3.0
        update_rubygems

    - name: Install dependencies
      run: |
        gem install bundler -v 2.2.33  # Compatible Bundler version
        bundle update --bundler
        bundle install

    - name: Install additional dependencies
      run: |
        npm install -g mermaid.cli

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if [[ ${GITHUB_REF} == refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "NO_PUSH=--no-push" >> $GITHUB_ENV
        elif [[ ${GITHUB_REF} == refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi

        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose ${{ env.NO_PUSH }} \
        --src ${{ env.SRC_BRANCH }} \
        --deploy ${{ env.DEPLOY_BRANCH }}
